### PR TITLE
Added PortableLibrary2.0 project targeting .NET Standard 2.0

### PR DESCRIPTION
**Pull request by owerkop**
#222

### CODE REVIEW

**Comment by Marusyk** [comment]
any plans when it can be merged?

**Comment by miketayo** [comment]
@owerkop is there any sample on usage with aspnet core.

Trying to migrate an MVC 5 app which used FluentScheduler v5+

Thanks

**Comment by tallesl** [comment]
Sorry, it's taking embarrassingly long to resolve this one. I plan to release a 5.4.0 in the coming weeks, targeting .NET standard 2.0.

However, I'll not be merging this pull request (sorry @owerkop). I'm developing exclusively with .NET Core on Linux for a good while and I can't remember the last time I've opened my full-blown Visual Studio.

I'll ditch the solution file (.sln) and also the portable library project, which I always found an oddity of a project.

**Comment by tallesl** [comment]
Available on [5.4.0](https://www.nuget.org/packages/FluentScheduler/5.4.0).

**Pull request closed without merging**
